baseURL = "/"
title = "Tim&Koko Brand Guide"
defaultContentLanguage = "de"
defaultContentLanguageInSubdir = false
enableRobotsTXT = true
disableKinds = ["taxonomy", "term"]

# add redirects/headers
[outputs]
  home = ["HTML", "REDIRECTS", "HEADERS"]

# remove .{ext} from text/netlify
[mediaTypes."text/netlify"]
  suffixes = [""]
  delimiter = ""

# add output format for netlify _redirects
[outputFormats.REDIRECTS]
  mediatype = "text/netlify"
  baseName = "_redirects"
  isPlainText = true
  notAlternative = true

# add output format for netlify _headers
[outputFormats.HEADERS]
  mediatype = "text/netlify"
  baseName = "_headers"
  isPlainText = true
  notAlternative = true

[languages]
  [languages.de]
    languageName = "Deutsch"
    weight = 1
    contentDir = "content/de"

  [languages.en]
    languageName = "English"
    weight = 2
    contentDir = "content/en"
